### ISSUE TITLE
startGymBattle response is empty status_code 3

### ISSUE THREAD

**Issue by dnsBlah** [keyphact/pgoapi#95] opened 2016-08-14 18:13 UTC
Hi all,

can you please help me out here.
I'm trying to start a gym battle.

```
startBattleResult = api.start_gym_battle(fortid=gymDetails['fort_data']['id'],
                                                             attacking_pokemon_ids=attackerIDS, #this is a list of my pokemon id's ( 6 if it's not my team, 1 if it's mine )
                                                             defending_pokemon_id=defenderID, # is the first pokemon.id of the defenders (not a list)
                                                             player_latitude=latitude, #self explaining
                                                             player_longitude=longitude) #self explaining
```
The results are always:
```
{   'request_id': 128508155905316952L,
    'responses': {   'START_GYM_BATTLE': {   }},
    'status_code': 3,
    'unknown6': [{   'response_type': 6, 'unknown2': {   'unknown1': 1L}}]}
```

**Comment by wchill** [comment] 2016-08-17 07:13
Dupe of #99

**Closed by wchill** 2016-08-17 07:13 UTC
